### ISSUE TITLE
什么时候出win版！

### ISSUE THREAD

**Issue by FancyangY** [soxft/serverStatus#1]
什么时候出win版！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by soxft** [comment]
没有适配windows的计划, 如有需要, 可以提pr

**Comment by Hua-Fan-Yang** [comment]
这是来自阳阳邮箱的自动回复邮件。你好，我最近很忙，无法亲自回复你的邮件。我将在忙完后，尽快给你回复。

**Comment by FancyangY** [comment]
我给你赞助一毛钱明天就出（（（
